// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import CtaBanner from "./CtaBanner/index.svelte";
import DonationForm from "./DonationForm/index.svelte";
import HeartHero from "./HeartHero/index.svelte";
import Hero from "./Hero/index.svelte";
import IconColumns from "./IconColumns/index.svelte";
import ImageBand from "./ImageBand/index.svelte";
import LeadText from "./LeadText/index.svelte";
import MediaText from "./MediaText/index.svelte";
import PageMasthead from "./PageMasthead/index.svelte";
import PersonGrid from "./PersonGrid/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import StatementPanel from "./StatementPanel/index.svelte";
import StatsBand from "./StatsBand/index.svelte";
import Testimonial from "./Testimonial/index.svelte";
import TextColumns from "./TextColumns/index.svelte";

export const components = {
  accordion: Accordion,
  cta_banner: CtaBanner,
  donation_form: DonationForm,
  heart_hero: HeartHero,
  hero: Hero,
  icon_columns: IconColumns,
  image_band: ImageBand,
  lead_text: LeadText,
  media_text: MediaText,
  page_masthead: PageMasthead,
  person_grid: PersonGrid,
  rich_text: RichText,
  section_grid: SectionGrid,
  statement_panel: StatementPanel,
  stats_band: StatsBand,
  testimonial: Testimonial,
  text_columns: TextColumns,
};
