// Code generated by Slice Machine. DO NOT EDIT.

import Accordion from "./Accordion/index.svelte";
import CtaBanner from "./CtaBanner/index.svelte";
import HeartHero from "./HeartHero/index.svelte";
import Hero from "./Hero/index.svelte";
import IconColumns from "./IconColumns/index.svelte";
import LeadText from "./LeadText/index.svelte";
import MediaText from "./MediaText/index.svelte";
import RichText from "./RichText/index.svelte";
import SectionGrid from "./SectionGrid/index.svelte";
import Testimonial from "./Testimonial/index.svelte";
import TextColumns from "./TextColumns/index.svelte";

export const components = {
  accordion: Accordion,
  cta_banner: CtaBanner,
  heart_hero: HeartHero,
  hero: Hero,
  icon_columns: IconColumns,
  lead_text: LeadText,
  media_text: MediaText,
  rich_text: RichText,
  section_grid: SectionGrid,
  testimonial: Testimonial,
  text_columns: TextColumns,
};
